version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: Asia/Taipei
    open-pull-requests-limit: 10
    groups:
      worker-tests:
        patterns:
          - vitest
          - "@cloudflare/vitest-pool-workers"
      npm-minor-and-patch:
        exclude-patterns:
          - "@types/vscode"
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:30"
      timezone: Asia/Taipei
    open-pull-requests-limit: 10
