export interface CompactPolicyCopy {
	updated: string;
	privacy: { intro: string; heading: string; body: string };
	support: { intro: string; heading: string; body: string };
	terms: { intro: string; heading: string; body: string };
}

type CompactPolicyLocale = 'ja' | 'ko' | 'de' | 'fr' | 'es' | 'it' | 'pt-br' | 'ru' | 'pl' | 'cs' | 'hu' | 'bg' | 'tr';

export const COMPACT_POLICY_LOCALES = {
	ja: {
		updated: '最終更新日：2026年8月20日',
		privacy: {
			intro: 'この方針は、「フィードバックを送る」と「自分のフィードバック」でのデータ処理を説明します。これは利用者が開始するサポート送信であり、テレメトリや行動分析ではありません。フォームを開いたり編集したりするだけでは送信されず、送信前に完全な内容が表示され、明示的な確認が必要です。',
			heading: '収集、処理、保存、削除、および利用者の権利',
			body: '必須項目は種類、題名、説明で、再現手順と期待結果は任意です。基本環境情報は既定で有効ですが無効にでき、アプリと VS Code のバージョン、OS の種類とメジャーバージョン、CPU 構成、言語、正規化したホスト／ワークスペースの種類、信頼状態、ボード、プログラミング言語、ツールの準備状態、安定したエラーコードだけを含みます。最近の構造化イベントは任意です。ソースコード、Blockly ワークスペース、生成コード、名前、パス、端末 ID、ポート、Wi-Fi、IP アドレス、環境変数、資格情報、生のエラーやログは自動送信しません。任意の画像は端末内で再エンコードしてメタデータを削除し、1920 ピクセル、3 MiB に制限しますが、見える個人情報は送信者が確認してください。256-bit の秘密は VS Code SecretStorage に保存され、サーバーは HMAC だけを保持します。復旧リンクは URL フラグメントを使い、交換後の HttpOnly・Secure・SameSite セッションは最長24時間です。Cloudflare は防御のため送信元 IP を短時間処理する場合がありますが、アプリは HMAC 派生値だけを使用します。本文は Cloudflare D1、画像は非公開 R2、保守用コピーは非公開 GitHub に保存され、国境を越えて処理される場合があります。内部メモは非公開で、明示した公開返信だけが利用者に表示されます。責任者が承認した匿名の公開開発 Issue は元の非公開項目にリンクしません。内容は削除まで保存され、冪等記録は7日、セッションは24時間、本文を含まない監査記録は90日以内です。削除により本文、メッセージ、画像、非公開 GitHub の原文を除去しますが、内容のない墓標、承認済みの匿名 Issue、提供者の暗号化バックアップは残る場合があります。生徒は個人情報を送らず、必要なら保護者や先生に確認してもらってください。「自分のフィードバック」または復旧リンクで閲覧・追記・削除できます。秘密を失うと所有権を確認できません。一般の問い合わせはサポート、安全上の問題は SECURITY.md の非公開手順を利用してください。',
		},
		support: {
			intro: 'Blockly エディターの「フィードバックを送る」またはコマンドパレットを使用します。GitHub アカウントは不要です。',
			heading: 'アクセス、削除、安全上の問い合わせ、サポート範囲',
			body: 'フィードバック番号と非公開の復旧リンクを安全に保管してください。このリンクは資格情報です。「自分のフィードバック」またはリンクで状態と公開返信を確認し、文章を追加し、1件または全部を削除できます。提供者バックアップと、責任者が承認した匿名の公開 Issue の例外はプライバシー方針に記載されています。悪用可能な脆弱性、秘密の漏えい、アクセス制御の問題は一般フィードバックや公開 Issue に書かず、SECURITY.md の GitHub Security Advisory を利用してください。サポートはベストエフォートで、応答時間、採用、再現性を保証しません。PlatformIO、GitHub、Cloudflare、VS Code／VSCodium、ハードウェア、ネットワークの状態に左右されます。プロジェクトのバックアップは各自で保持してください。',
		},
		terms: {
			intro: 'Singular Blockly の任意のフィードバックサービスを使用すると、この利用条件とプライバシー方針に同意したことになります。サービスを使わなくても製品は利用できます。',
			heading: '目的、利用者の責任、権利、制限',
			body: '本サービスは製品の問題、機能提案、使用上の質問、その他のフィードバック専用で、返答、修正、採用、予定、公開を保証しません。共有する権利のある内容だけを送信し、文章と画像を事前に確認してください。違法、権利侵害、嫌がらせ、なりすまし、悪意ある内容、スパム、自動化された乱用、資格情報、大量の無関係な内容を送ったり、制限や認証を回避したりしてはいけません。利用者は内容の権利を保持し、保守担当者にサポート、診断、分類、改善に必要な非独占的利用を許可します。責任者の承認後は、元の報告者や非公開項目に結び付かない匿名の公開 Issue を作成でき、非公開データの削除後も残る場合があります。安全性と可用性のため、レート制限、拒否、スパムの終了、匿名資格情報の無効化を行う場合があります。本サービスは現状有姿で、中断、遅延、変更、終了することがあります。緊急事態、生命・機器の安全、法的通知、プロジェクトのバックアップには使用しないでください。一般の連絡はサポート、安全上の連絡は SECURITY.md を利用してください。',
		},
	},
	ko: {
		updated: '마지막 업데이트: 2026년 8월 20일',
		privacy: {
			intro: '이 정책은 ‘피드백 보내기’와 ‘내 피드백’이 데이터를 처리하는 방식을 설명해요. 사용자가 직접 시작하는 지원 전송이며 원격 측정이나 행동 분석이 아니에요. 양식을 열거나 편집하는 것만으로는 전송되지 않고, 보내기 전에 전체 내용과 명시적 확인을 제공해요.',
			heading: '수집, 처리, 보관, 삭제 및 권리',
			body: '필수 항목은 종류, 제목, 설명이며 재현 단계와 예상 결과는 선택 사항이에요. 기본 환경 정보는 기본적으로 켜져 있지만 끌 수 있고 앱 및 VS Code 버전, 운영 체제 종류와 주 버전, CPU 구조, 언어, 정규화된 호스트와 작업 영역 종류, 신뢰 상태, 보드, 프로그래밍 언어, 도구 준비 상태, 안정적인 오류 코드만 포함해요. 최근 구조화 이벤트는 별도 선택 사항이에요. 소스 코드, Blockly 작업 영역, 생성 코드, 이름, 경로, 장치 ID, 포트, Wi-Fi, IP 주소, 환경 변수, 자격 증명, 원본 오류나 로그는 자동으로 보내지 않아요. 선택한 이미지는 기기에서 다시 인코딩하고 메타데이터를 없애며 1920픽셀과 3MiB로 제한하지만 화면에 보이는 개인정보는 보내기 전에 확인해야 해요. 256-bit 비밀값은 VS Code SecretStorage에 저장되고 서버에는 HMAC만 남아요. 복구 링크는 URL 프래그먼트를 사용하고 교환 뒤 HttpOnly·Secure·SameSite 세션은 최대 24시간이에요. Cloudflare는 보호를 위해 원본 IP를 잠시 처리할 수 있지만 앱은 HMAC 파생값만 사용해요. 본문은 Cloudflare D1, 이미지는 비공개 R2, 유지관리 사본은 비공개 GitHub에 저장되며 국경을 넘어 처리될 수 있어요. 내부 메모는 비공개이고 명시적 공개 답변만 사용자에게 보여요. 책임자가 승인한 익명 공개 개발 Issue는 원래 비공개 항목에 연결되지 않아요. 내용은 삭제할 때까지 보관하며 멱등 기록은 7일, 세션은 24시간, 본문 없는 감사 기록은 90일 이내예요. 삭제하면 본문, 메시지, 이미지와 비공개 GitHub 원문이 제거되지만 내용 없는 삭제 표식, 승인된 익명 Issue, 제공업체의 암호화 백업은 남을 수 있어요. 학생은 개인정보를 보내지 말고 필요하면 보호자나 교사에게 확인을 부탁하세요. ‘내 피드백’ 또는 복구 링크에서 조회·추가·삭제할 수 있어요. 비밀값을 잃으면 소유권을 확인할 수 없어요. 일반 문의는 지원 페이지, 보안 문제는 SECURITY.md의 비공개 절차를 이용하세요.',
		},
		support: {
			intro: 'Blockly 편집기의 ‘피드백 보내기’ 또는 명령 팔레트를 사용하세요. GitHub 계정은 필요하지 않아요.',
			heading: '접근, 삭제, 보안 문의 및 지원 범위',
			body: '피드백 번호와 비공개 복구 링크를 안전하게 보관하세요. 링크는 자격 증명이에요. ‘내 피드백’이나 링크에서 상태와 공개 답변을 보고, 글을 추가하고, 한 건 또는 모두 삭제할 수 있어요. 제공업체 백업 및 책임자가 승인한 익명 공개 Issue 예외는 개인정보 보호정책에 설명되어 있어요. 악용 가능한 취약점, 비밀 유출, 접근 제어 문제는 일반 피드백이나 공개 Issue에 쓰지 말고 SECURITY.md의 GitHub Security Advisory를 사용하세요. 지원은 최선을 다해 제공되며 응답 시간, 반영, 재현을 보장하지 않아요. PlatformIO, GitHub, Cloudflare, VS Code／VSCodium, 하드웨어와 네트워크 상태가 결과에 영향을 줄 수 있어요. 프로젝트 백업은 직접 보관하세요.',
		},
		terms: {
			intro: '선택 사항인 Singular Blockly 피드백 서비스를 사용하면 이 약관과 개인정보 보호정책에 동의하게 돼요. 서비스를 사용하지 않아도 제품은 계속 사용할 수 있어요.',
			heading: '목적, 사용자 책임, 권리 및 제한',
			body: '서비스는 제품 문제, 기능 제안, 사용 질문 및 기타 피드백만을 위한 것이며 답변, 수정, 반영, 일정 또는 출시를 보장하지 않아요. 공유할 권리가 있는 내용만 보내고 모든 글과 이미지를 먼저 확인하세요. 불법, 권리 침해, 괴롭힘, 사칭, 악성 콘텐츠, 스팸, 자동화된 남용, 자격 증명 또는 무관한 대량 콘텐츠를 보내거나 제한과 인증을 우회하면 안 돼요. 사용자는 콘텐츠 권리를 유지하며 유지관리자에게 지원, 진단, 분류 및 개선에 필요한 비독점 권한을 부여해요. 책임자 승인 뒤 원래 사용자나 비공개 항목과 연결되지 않는 익명 공개 Issue를 만들 수 있으며 비공개 데이터 삭제 후에도 남을 수 있어요. 보안과 가용성을 위해 요청 제한, 거부, 스팸 종료 또는 익명 자격 증명 철회를 할 수 있어요. 서비스는 현 상태로 제공되며 중단, 지연, 변경 또는 종료될 수 있어요. 긴급 상황, 생명·장비 안전, 법적 통지 또는 프로젝트 백업에 사용하지 마세요. 일반 문의는 지원 페이지, 보안 문의는 SECURITY.md를 이용하세요.',
		},
	},
	de: {
		updated: 'Zuletzt aktualisiert: 20. August 2026',
		privacy: {
			intro: 'Diese Richtlinie erklärt die Datenverarbeitung in „Feedback geben“ und „Mein Feedback“. Es handelt sich um eine von dir gestartete Supportübermittlung, nicht um Telemetrie oder Verhaltensanalyse. Beim Öffnen oder Bearbeiten wird nichts gesendet; vor dem Senden siehst du den vollständigen Inhalt und musst ausdrücklich zustimmen.',
			heading: 'Erhebung, Verarbeitung, Speicherung, Löschung und Rechte',
			body: 'Pflichtangaben sind Art, Titel und Beschreibung; Schritte und erwartetes Ergebnis sind optional. Basis-Umgebungsdaten sind standardmäßig aktiv, aber abschaltbar, und umfassen nur App- und VS-Code-Version, Betriebssystemfamilie und Hauptversion, Architektur, Sprache, normalisierte Host- und Arbeitsbereichsart, Vertrauensstatus, Board, Programmiersprache, Werkzeugbereitschaft und stabile Fehlercodes. Letzte strukturierte Ereignisse sind separat optional. Quellcode, Blockly-Arbeitsbereich, erzeugter Code, Namen, Pfade, Geräte-IDs, Ports, Wi-Fi, IP-Adressen, Umgebungsvariablen, Zugangsdaten, rohe Fehler oder Protokolle werden nicht automatisch gesendet. Ein freiwilliges Bild wird lokal neu kodiert, von Metadaten befreit und auf 1920 Pixel sowie 3 MiB begrenzt; sichtbare persönliche Angaben musst du selbst prüfen. Das 256-bit-Geheimnis liegt in VS Code SecretStorage, der Server speichert nur einen HMAC. Der Wiederherstellungslink nutzt ein URL-Fragment; danach gilt eine HttpOnly-, Secure- und SameSite-Sitzung höchstens 24 Stunden. Cloudflare kann die Quell-IP kurz zum Schutz verarbeiten, die Anwendung verwendet nur einen HMAC-Wert. Text liegt in Cloudflare D1, Bilder in privatem R2 und die Arbeitskopie in einem privaten GitHub-Repository; eine grenzüberschreitende Verarbeitung ist möglich. Interne Notizen bleiben privat, nur ausdrücklich öffentliche Antworten werden angezeigt. Ein vom Verantwortlichen genehmigtes anonymisiertes öffentliches Entwicklungs-Issue wird nicht mit dem privaten Eintrag verknüpft. Inhalte bleiben bis zur Löschung; Idempotenzdaten 7 Tage, Sitzungen 24 Stunden und inhaltsfreie Prüfdaten höchstens 90 Tage. Die Löschung entfernt Text, Nachrichten, Bilder und privaten GitHub-Originalinhalt; inhaltsfreie Löschmarken, genehmigte anonyme Issues und verschlüsselte Anbieter-Backups können bleiben. Schüler sollen keine persönlichen Daten senden und bei Bedarf Eltern oder Lehrkräfte einbeziehen. Mit „Mein Feedback“ oder dem Link kannst du lesen, ergänzen und löschen. Ohne Geheimnis ist der Besitz nicht nachweisbar. Allgemeine Anfragen gehören zum Support, Sicherheitsprobleme zum privaten Verfahren in SECURITY.md.',
		},
		support: {
			intro: 'Nutze „Feedback geben“ im Blockly-Editor oder die Befehlspalette. Ein GitHub-Konto ist nicht nötig.',
			heading: 'Zugriff, Löschung, Sicherheitsmeldungen und Umfang',
			body: 'Bewahre Feedbacknummer und privaten Wiederherstellungslink sicher auf; der Link ist ein Zugangsnachweis. Über „Mein Feedback“ oder den Link kannst du Status und öffentliche Antworten sehen, Text ergänzen und einzelne oder alle Meldungen löschen. Ausnahmen für Anbieter-Backups und verantwortliche genehmigte anonyme öffentliche Issues stehen in der Datenschutzrichtlinie. Ausnutzbare Schwachstellen, offengelegte Geheimnisse oder Zugriffskontrollfehler gehören nicht in allgemeines Feedback oder öffentliche Issues, sondern in das GitHub Security Advisory aus SECURITY.md. Support erfolgt nach Möglichkeit, ohne Garantie für Antwortzeit, Umsetzung oder Reproduzierbarkeit. PlatformIO, GitHub, Cloudflare, VS Code/VSCodium, Hardware und Netzwerk können das Ergebnis beeinflussen. Sichere dein Projekt selbst.',
		},
		terms: {
			intro: 'Mit dem optionalen Singular-Blockly-Feedbackdienst akzeptierst du diese Bedingungen und die Datenschutzrichtlinie. Das Produkt bleibt auch ohne den Dienst nutzbar.',
			heading: 'Zweck, Verantwortung, Rechte und Beschränkungen',
			body: 'Der Dienst ist nur für Produktprobleme, Funktionswünsche, Nutzungsfragen und anderes Feedback bestimmt und verspricht keine Antwort, Korrektur, Umsetzung, Planung oder Veröffentlichung. Sende nur Inhalte, die du teilen darfst, und prüfe Text und Bilder vorher. Unzulässig sind rechtswidrige, verletzende, belästigende, täuschende oder schädliche Inhalte, Spam, automatisierter Missbrauch, Zugangsdaten, sachfremde Masseninhalte sowie das Umgehen von Limits oder Authentifizierung. Du behältst deine Rechte und erteilst den Betreuern die nicht ausschließliche Erlaubnis, die für Support, Diagnose, Einordnung und Verbesserung nötig ist. Nach Genehmigung kann ein anonymes öffentliches Issue ohne Verbindung zu dir oder dem privaten Eintrag entstehen und nach dessen Löschung bestehen bleiben. Zum Schutz kann der Dienst begrenzen, ablehnen, Spam schließen oder anonyme Zugangsdaten widerrufen. Er wird wie vorhanden bereitgestellt und kann ausfallen, sich verzögern, ändern oder enden. Nutze ihn nicht für Notfälle, Lebens- oder Gerätesicherheit, rechtliche Mitteilungen oder Projektsicherungen. Allgemeiner Kontakt erfolgt über Support, Sicherheitskontakt über SECURITY.md.',
		},
	},
	fr: {
		updated: 'Dernière mise à jour : 20 août 2026',
		privacy: {
			intro: 'Cette politique explique le traitement des données dans « Envoyer un retour » et « Mes retours ». Il s’agit d’un envoi d’assistance déclenché par vous, et non de télémétrie ou d’analyse du comportement. Ouvrir ou modifier le formulaire ne transmet rien ; le contenu complet est affiché et votre confirmation explicite est requise avant l’envoi.',
			heading: 'Collecte, traitement, conservation, suppression et droits',
			body: 'Le type, le titre et la description sont obligatoires ; les étapes et le résultat attendu sont facultatifs. Les informations d’environnement de base sont activées par défaut mais désactivables et se limitent aux versions de l’application et de VS Code, à la famille et version majeure du système, à l’architecture, à la langue, aux types normalisés d’hôte et d’espace de travail, à la confiance, à la carte, au langage, à l’état des outils et aux codes d’erreur stables. Les événements structurés récents sont facultatifs séparément. Le code source, l’espace Blockly, le code généré, les noms, chemins, identifiants d’appareil, ports, Wi-Fi, adresses IP, variables d’environnement, secrets, erreurs brutes et journaux ne sont pas envoyés automatiquement. Une image facultative est réencodée localement, sans métadonnées, et limitée à 1920 pixels et 3 Mio ; vérifiez toute donnée personnelle visible. Le secret de 256-bit reste dans VS Code SecretStorage et le serveur ne garde qu’un HMAC. Le lien de récupération utilise le fragment d’URL ; la session HttpOnly, Secure et SameSite qui suit dure au plus 24 heures. Cloudflare peut traiter brièvement l’IP source pour la protection, tandis que l’application n’utilise qu’une valeur HMAC. Le texte est dans Cloudflare D1, les images dans R2 privé et la copie de maintenance dans GitHub privé ; un traitement transfrontalier est possible. Les notes internes restent privées et seules les réponses explicitement publiques sont visibles. Un Issue public anonymisé approuvé par le responsable n’est pas relié au dossier privé. Le contenu reste jusqu’à suppression ; l’idempotence 7 jours, les sessions 24 heures et l’audit sans contenu au plus 90 jours. La suppression retire texte, messages, images et contenu GitHub privé, mais une marque sans contenu, un Issue anonyme approuvé et des sauvegardes chiffrées du fournisseur peuvent subsister. Les élèves ne doivent pas envoyer de données personnelles et doivent demander l’aide d’un adulte si nécessaire. « Mes retours » ou le lien permet de consulter, compléter et supprimer. Sans le secret, la propriété ne peut être prouvée. Utilisez l’assistance pour les demandes générales et la procédure privée de SECURITY.md pour la sécurité.',
		},
		support: {
			intro: 'Utilisez « Envoyer un retour » dans l’éditeur Blockly ou la palette de commandes. Aucun compte GitHub n’est nécessaire.',
			heading: 'Accès, suppression, sécurité et portée de l’assistance',
			body: 'Conservez le numéro et le lien privé de récupération en lieu sûr : le lien est un identifiant d’accès. « Mes retours » ou le lien permet de voir l’état et les réponses publiques, d’ajouter du texte et de supprimer un retour ou tous les retours. Les exceptions relatives aux sauvegardes et aux Issues publics anonymisés approuvés figurent dans la politique de confidentialité. Ne placez pas une vulnérabilité exploitable, un secret divulgué ou un défaut de contrôle d’accès dans un retour général ou un Issue public ; utilisez le GitHub Security Advisory décrit dans SECURITY.md. L’assistance est fournie au mieux, sans garantie de délai, d’adoption ni de reproductibilité. PlatformIO, GitHub, Cloudflare, VS Code/VSCodium, le matériel et le réseau peuvent influencer le résultat. Gardez votre propre sauvegarde du projet.',
		},
		terms: {
			intro: 'En utilisant le service facultatif de retours Singular Blockly, vous acceptez ces conditions et la politique de confidentialité. Le produit reste utilisable sans ce service.',
			heading: 'Objet, responsabilités, droits et limitations',
			body: 'Le service sert uniquement aux problèmes du produit, suggestions de fonctions, questions d’utilisation et autres retours ; il ne garantit ni réponse, ni correction, ni adoption, ni calendrier, ni publication. N’envoyez que du contenu que vous êtes autorisé à partager et vérifiez textes et images. Sont interdits les contenus illégaux, contrefaisants, harcelants, usurpés ou malveillants, le spam, l’abus automatisé, les secrets, les envois massifs sans rapport et le contournement des limites ou de l’authentification. Vous conservez vos droits et accordez aux mainteneurs l’autorisation non exclusive nécessaire à l’assistance, au diagnostic, au tri et à l’amélioration. Après approbation, un Issue public anonymisé sans lien avec vous ni le dossier privé peut être créé et rester après suppression. Pour la sécurité, le service peut limiter, refuser, fermer le spam ou révoquer un identifiant anonyme. Il est fourni en l’état et peut être interrompu, retardé, modifié ou arrêté. Ne l’utilisez pas pour une urgence, la sécurité des personnes ou du matériel, une notification juridique ou une sauvegarde. Contact général via l’assistance ; sécurité via SECURITY.md.',
		},
	},
	es: {
		updated: 'Última actualización: 20 de agosto de 2026',
		privacy: {
			intro: 'Esta política explica el tratamiento de datos en «Enviar comentarios» y «Mis comentarios». Es un envío de soporte iniciado por ti, no telemetría ni análisis del comportamiento. Abrir o editar el formulario no transmite nada; antes de enviar se muestra el contenido completo y se exige confirmación explícita.',
			heading: 'Recopilación, tratamiento, conservación, eliminación y derechos',
			body: 'Son obligatorios el tipo, el título y la descripción; los pasos y el resultado esperado son opcionales. La información básica del entorno está activada de forma predeterminada, pero se puede desactivar, y se limita a las versiones de la aplicación y VS Code, familia y versión principal del sistema, arquitectura, idioma, tipos normalizados de host y espacio de trabajo, confianza, placa, lenguaje, disponibilidad de herramientas y códigos de error estables. Los eventos estructurados recientes son opcionales por separado. No se envían automáticamente código fuente, espacio Blockly, código generado, nombres, rutas, identificadores de dispositivos, puertos, Wi-Fi, direcciones IP, variables de entorno, credenciales, errores sin procesar ni registros. Una imagen opcional se recodifica localmente, elimina metadatos y se limita a 1920 píxeles y 3 MiB; revisa los datos personales visibles. El secreto de 256-bit queda en VS Code SecretStorage y el servidor solo conserva un HMAC. El enlace de recuperación usa el fragmento de URL; después, la sesión HttpOnly, Secure y SameSite dura como máximo 24 horas. Cloudflare puede procesar brevemente la IP de origen para protección, mientras la aplicación solo usa un valor HMAC. El texto se guarda en Cloudflare D1, las imágenes en R2 privado y la copia de mantenimiento en GitHub privado; puede haber tratamiento transfronterizo. Las notas internas son privadas y solo se muestran respuestas marcadas expresamente como públicas. Un Issue público anonimizado aprobado por el responsable no se vincula al elemento privado. El contenido se conserva hasta eliminarlo; la idempotencia 7 días, las sesiones 24 horas y la auditoría sin contenido un máximo de 90 días. La eliminación quita texto, mensajes, imágenes y contenido original privado de GitHub, aunque pueden quedar una marca sin contenido, un Issue anónimo aprobado y copias de seguridad cifradas del proveedor. Los estudiantes no deben enviar datos personales y deben pedir ayuda a un adulto cuando corresponda. «Mis comentarios» o el enlace permiten consultar, añadir y eliminar. Sin el secreto no puede demostrarse la propiedad. Usa soporte para consultas generales y el proceso privado de SECURITY.md para seguridad.',
		},
		support: {
			intro: 'Usa «Enviar comentarios» en el editor Blockly o la paleta de comandos. No necesitas una cuenta de GitHub.',
			heading: 'Acceso, eliminación, seguridad y alcance del soporte',
			body: 'Guarda de forma segura el número y el enlace privado de recuperación; el enlace es una credencial. «Mis comentarios» o el enlace permiten ver el estado y las respuestas públicas, añadir texto y eliminar uno o todos los comentarios. Las excepciones de copias de seguridad y de Issues públicos anónimos aprobados se explican en la política de privacidad. No publiques vulnerabilidades explotables, secretos filtrados ni fallos de control de acceso en comentarios generales o Issues públicos; usa el GitHub Security Advisory indicado en SECURITY.md. El soporte se presta según disponibilidad, sin garantizar plazo, adopción ni reproducción. PlatformIO, GitHub, Cloudflare, VS Code/VSCodium, el hardware y la red pueden afectar el resultado. Conserva tu propia copia del proyecto.',
		},
		terms: {
			intro: 'Al usar el servicio opcional de comentarios de Singular Blockly, aceptas estas condiciones y la política de privacidad. Puedes seguir usando el producto sin el servicio.',
			heading: 'Finalidad, responsabilidades, derechos y limitaciones',
			body: 'El servicio es solo para problemas del producto, sugerencias, preguntas de uso y otros comentarios; no promete respuesta, corrección, adopción, calendario ni publicación. Envía únicamente contenido que puedas compartir y revisa texto e imágenes. Se prohíben contenidos ilegales, infractores, acosadores, suplantados o maliciosos, spam, abuso automatizado, credenciales, envíos masivos no relacionados y eludir límites o autenticación. Conservas tus derechos y concedes a los mantenedores el permiso no exclusivo necesario para soporte, diagnóstico, clasificación y mejora. Tras aprobación puede crearse un Issue público anonimizado sin relación contigo ni con el elemento privado, y puede permanecer después de eliminar los datos privados. Para proteger el servicio se pueden limitar o rechazar solicitudes, cerrar spam o revocar credenciales anónimas. Se ofrece tal cual y puede interrumpirse, retrasarse, cambiar o finalizar. No lo uses para emergencias, seguridad personal o del equipo, avisos legales ni copias de seguridad. Contacto general mediante soporte; seguridad mediante SECURITY.md.',
		},
	},
	it: {
		updated: 'Ultimo aggiornamento: 20 agosto 2026',
		privacy: {
			intro: 'Questa informativa spiega il trattamento dei dati in “Invia feedback” e “I miei feedback”. È un invio di assistenza avviato dall’utente, non telemetria né analisi del comportamento. Aprire o modificare il modulo non trasmette dati; prima dell’invio vengono mostrati tutti i contenuti ed è richiesta una conferma esplicita.',
			heading: 'Raccolta, trattamento, conservazione, eliminazione e diritti',
			body: 'Tipo, titolo e descrizione sono obbligatori; passaggi e risultato atteso sono facoltativi. Le informazioni di base sull’ambiente sono attive per impostazione predefinita ma disattivabili e comprendono solo versioni dell’app e di VS Code, famiglia e versione principale del sistema, architettura, lingua, tipi normalizzati di host e area di lavoro, attendibilità, scheda, linguaggio, disponibilità degli strumenti e codici di errore stabili. Gli eventi strutturati recenti sono facoltativi a parte. Non vengono inviati automaticamente codice sorgente, area Blockly, codice generato, nomi, percorsi, ID dei dispositivi, porte, Wi-Fi, indirizzi IP, variabili d’ambiente, credenziali, errori grezzi o registri. Un’immagine facoltativa viene ricodificata in locale, privata dei metadati e limitata a 1920 pixel e 3 MiB; controlla i dati personali visibili. Il segreto di 256-bit resta in VS Code SecretStorage e il server conserva solo un HMAC. Il link di recupero usa il frammento URL; la successiva sessione HttpOnly, Secure e SameSite dura al massimo 24 ore. Cloudflare può trattare brevemente l’IP sorgente per protezione, mentre l’app usa solo un valore HMAC. Il testo è in Cloudflare D1, le immagini in R2 privato e la copia di manutenzione in GitHub privato; è possibile un trattamento transfrontaliero. Le note interne restano private e sono visibili solo le risposte dichiarate pubbliche. Un Issue pubblico anonimizzato approvato dal responsabile non è collegato alla voce privata. Il contenuto resta fino all’eliminazione; idempotenza 7 giorni, sessioni 24 ore e controllo senza contenuti al massimo 90 giorni. L’eliminazione rimuove testo, messaggi, immagini e contenuto GitHub privato, ma possono restare una marcatura senza contenuto, un Issue anonimo approvato e backup cifrati del fornitore. Gli studenti non devono inviare dati personali e dovrebbero chiedere aiuto a un adulto quando serve. “I miei feedback” o il link consentono di vedere, aggiungere ed eliminare. Senza il segreto non si può provare la titolarità. Usa l’assistenza per richieste generali e la procedura privata in SECURITY.md per la sicurezza.',
		},
		support: {
			intro: 'Usa “Invia feedback” nell’editor Blockly o la tavolozza comandi. Non serve un account GitHub.',
			heading: 'Accesso, eliminazione, sicurezza e ambito dell’assistenza',
			body: 'Conserva al sicuro il numero e il link privato di recupero: il link è una credenziale. “I miei feedback” o il link consentono di vedere stato e risposte pubbliche, aggiungere testo ed eliminare uno o tutti i feedback. Le eccezioni per backup del fornitore e Issues pubblici anonimi approvati sono descritte nell’informativa sulla privacy. Non inserire vulnerabilità sfruttabili, segreti divulgati o problemi di controllo accessi nel feedback generale o in Issues pubblici; usa il GitHub Security Advisory indicato in SECURITY.md. L’assistenza è fornita al meglio, senza garanzia di tempi, adozione o riproducibilità. PlatformIO, GitHub, Cloudflare, VS Code/VSCodium, hardware e rete possono influire. Conserva un backup del progetto.',
		},
		terms: {
			intro: 'Usando il servizio facoltativo di feedback Singular Blockly accetti questi termini e l’informativa sulla privacy. Puoi continuare a usare il prodotto senza il servizio.',
			heading: 'Scopo, responsabilità, diritti e limitazioni',
			body: 'Il servizio è solo per problemi del prodotto, proposte di funzioni, domande d’uso e altri feedback; non promette risposta, correzione, adozione, programma o pubblicazione. Invia solo contenuti che puoi condividere e controlla testo e immagini. Sono vietati contenuti illegali, lesivi, molesti, impersonati o dannosi, spam, abuso automatico, credenziali, invii massivi non pertinenti e l’aggiramento di limiti o autenticazione. Mantieni i tuoi diritti e concedi ai manutentori il permesso non esclusivo necessario per assistenza, diagnosi, classificazione e miglioramento. Dopo approvazione può essere creato un Issue pubblico anonimizzato senza collegamento a te o alla voce privata e può restare dopo l’eliminazione. Per protezione il servizio può limitare, rifiutare, chiudere spam o revocare credenziali anonime. È fornito così com’è e può interrompersi, ritardare, cambiare o terminare. Non usarlo per emergenze, sicurezza di persone o hardware, comunicazioni legali o backup. Contatto generale tramite assistenza; sicurezza tramite SECURITY.md.',
		},
	},
	'pt-br': {
		updated: 'Última atualização: 20 de agosto de 2026',
		privacy: {
			intro: 'Esta política explica o tratamento de dados em “Enviar feedback” e “Meus feedbacks”. É um envio de suporte iniciado por você, não telemetria nem análise de comportamento. Abrir ou editar o formulário não transmite dados; antes do envio, todo o conteúdo é mostrado e exige confirmação explícita.',
			heading: 'Coleta, tratamento, retenção, exclusão e direitos',
			body: 'Tipo, título e descrição são obrigatórios; etapas e resultado esperado são opcionais. As informações básicas do ambiente ficam ativas por padrão, mas podem ser desativadas, e se limitam às versões do aplicativo e do VS Code, família e versão principal do sistema, arquitetura, idioma, tipos normalizados de host e espaço de trabalho, confiança, placa, linguagem, disponibilidade de ferramentas e códigos de erro estáveis. Eventos estruturados recentes são opcionais separadamente. Não são enviados automaticamente código-fonte, espaço Blockly, código gerado, nomes, caminhos, IDs de dispositivos, portas, Wi-Fi, endereços IP, variáveis de ambiente, credenciais, erros brutos ou registros. Uma imagem opcional é recodificada localmente, perde os metadados e fica limitada a 1920 pixels e 3 MiB; confira dados pessoais visíveis. O segredo de 256-bit fica no VS Code SecretStorage e o servidor guarda apenas um HMAC. O link de recuperação usa o fragmento da URL; depois, a sessão HttpOnly, Secure e SameSite dura no máximo 24 horas. A Cloudflare pode processar brevemente o IP de origem para proteção, enquanto o aplicativo usa apenas um valor HMAC. O texto fica no Cloudflare D1, as imagens no R2 privado e a cópia de manutenção no GitHub privado; pode ocorrer tratamento internacional. Notas internas ficam privadas e só respostas marcadas explicitamente como públicas aparecem. Um Issue público anonimizado aprovado pelo responsável não é ligado ao item privado. O conteúdo fica até a exclusão; idempotência por 7 dias, sessões por 24 horas e auditoria sem conteúdo por no máximo 90 dias. A exclusão remove texto, mensagens, imagens e conteúdo original privado do GitHub, mas podem permanecer uma marca sem conteúdo, um Issue anônimo aprovado e backups criptografados do fornecedor. Estudantes não devem enviar dados pessoais e devem pedir ajuda a um adulto quando necessário. “Meus feedbacks” ou o link permitem consultar, complementar e excluir. Sem o segredo não é possível provar a titularidade. Use o suporte para dúvidas gerais e o processo privado de SECURITY.md para segurança.',
		},
		support: {
			intro: 'Use “Enviar feedback” no editor Blockly ou a paleta de comandos. Não é preciso ter conta no GitHub.',
			heading: 'Acesso, exclusão, segurança e escopo do suporte',
			body: 'Guarde o número e o link privado de recuperação com segurança; o link é uma credencial. “Meus feedbacks” ou o link permitem ver o status e respostas públicas, adicionar texto e excluir um ou todos os feedbacks. As exceções de backups do fornecedor e Issues públicos anônimos aprovados estão na política de privacidade. Não coloque vulnerabilidades exploráveis, segredos expostos ou falhas de controle de acesso em feedback geral ou Issues públicos; use o GitHub Security Advisory indicado em SECURITY.md. O suporte é oferecido na medida do possível, sem garantia de prazo, adoção ou reprodução. PlatformIO, GitHub, Cloudflare, VS Code/VSCodium, hardware e rede podem afetar o resultado. Mantenha seu próprio backup do projeto.',
		},
		terms: {
			intro: 'Ao usar o serviço opcional de feedback do Singular Blockly, você aceita estes termos e a política de privacidade. O produto continua disponível sem o serviço.',
			heading: 'Finalidade, responsabilidades, direitos e limitações',
			body: 'O serviço é apenas para problemas do produto, sugestões de recursos, dúvidas de uso e outros feedbacks; não promete resposta, correção, adoção, cronograma nem publicação. Envie somente conteúdo que possa compartilhar e revise texto e imagens. São proibidos conteúdos ilegais, infratores, assediadores, falsos ou maliciosos, spam, abuso automatizado, credenciais, envios em massa sem relação e tentativas de contornar limites ou autenticação. Você mantém seus direitos e concede aos mantenedores a permissão não exclusiva necessária para suporte, diagnóstico, triagem e melhoria. Após aprovação, pode ser criado um Issue público anonimizado sem ligação com você ou o item privado, que pode permanecer depois da exclusão. Para proteção, o serviço pode limitar, rejeitar, fechar spam ou revogar credenciais anônimas. Ele é fornecido no estado em que se encontra e pode ser interrompido, atrasado, alterado ou encerrado. Não o use para emergências, segurança de pessoas ou equipamentos, avisos legais ou backup. Contato geral pelo suporte; segurança por SECURITY.md.',
		},
	},
	ru: {
		updated: 'Последнее обновление: 20 августа 2026 г.',
		privacy: {
			intro: 'Эта политика описывает обработку данных в функциях «Отправить отзыв» и «Мои отзывы». Это отправка в службу поддержки по инициативе пользователя, а не телеметрия или анализ поведения. При открытии и редактировании формы данные не передаются; перед отправкой показывается всё содержимое и требуется явное подтверждение.',
			heading: 'Сбор, обработка, хранение, удаление и права',
			body: 'Обязательны тип, заголовок и описание; шаги и ожидаемый результат необязательны. Базовые сведения о среде включены по умолчанию, но их можно отключить; они ограничены версиями приложения и VS Code, семейством и основной версией ОС, архитектурой, языком, нормализованными типами хоста и рабочей области, доверием, платой, языком программирования, готовностью инструментов и стабильными кодами ошибок. Недавние структурированные события включаются отдельно. Исходный код, область Blockly, созданный код, имена, пути, идентификаторы устройств, порты, Wi-Fi, IP-адреса, переменные среды, учётные данные, необработанные ошибки и журналы автоматически не отправляются. Необязательное изображение локально перекодируется, очищается от метаданных и ограничивается 1920 пикселями и 3 МиБ; проверьте видимые персональные данные. Секрет 256-bit хранится в VS Code SecretStorage, сервер хранит только HMAC. Ссылка восстановления использует фрагмент URL; последующий сеанс HttpOnly, Secure и SameSite действует не более 24 часов. Cloudflare может кратковременно обрабатывать исходный IP для защиты, а приложение использует только значение HMAC. Текст хранится в Cloudflare D1, изображения — в закрытом R2, рабочая копия — в закрытом GitHub; возможна трансграничная обработка. Внутренние заметки закрыты, пользователю видны только явно публичные ответы. Одобренный ответственным анонимный публичный Issue не связывается с закрытой записью. Содержимое хранится до удаления; данные идемпотентности — 7 дней, сеансы — 24 часа, аудит без содержимого — не более 90 дней. Удаляются текст, сообщения, изображения и исходное содержимое закрытого GitHub, но могут сохраниться пустая метка удаления, одобренный анонимный Issue и зашифрованные резервные копии поставщика. Учащимся не следует отправлять персональные данные; при необходимости нужно обратиться к взрослому. «Мои отзывы» или ссылка позволяют просматривать, дополнять и удалять. Без секрета право владения подтвердить нельзя. Общие вопросы направляйте в поддержку, вопросы безопасности — по закрытой процедуре SECURITY.md.',
		},
		support: {
			intro: 'Используйте «Отправить отзыв» в редакторе Blockly или палитру команд. Учётная запись GitHub не требуется.',
			heading: 'Доступ, удаление, безопасность и объём поддержки',
			body: 'Храните номер и закрытую ссылку восстановления в безопасности: ссылка является учётным секретом. Через «Мои отзывы» или ссылку можно видеть статус и публичные ответы, добавлять текст и удалять одну или все записи. Исключения для резервных копий поставщика и одобренных анонимных публичных Issues описаны в политике конфиденциальности. Не публикуйте эксплуатируемые уязвимости, раскрытые секреты или ошибки контроля доступа в обычном отзыве или публичном Issue; используйте GitHub Security Advisory из SECURITY.md. Поддержка предоставляется по возможности без гарантии срока ответа, принятия или воспроизводимости. На результат могут влиять PlatformIO, GitHub, Cloudflare, VS Code/VSCodium, оборудование и сеть. Храните собственную резервную копию проекта.',
		},
		terms: {
			intro: 'Используя необязательный сервис отзывов Singular Blockly, вы принимаете эти условия и политику конфиденциальности. Продукт можно использовать без сервиса.',
			heading: 'Назначение, ответственность, права и ограничения',
			body: 'Сервис предназначен только для сообщений о продукте, предложений функций, вопросов по использованию и других отзывов; он не обещает ответа, исправления, принятия, срока или выпуска. Отправляйте только то, чем вправе делиться, и заранее проверяйте текст и изображения. Запрещены незаконные, нарушающие права, оскорбительные, выдаваемые за чужие или вредоносные материалы, спам, автоматизированное злоупотребление, учётные данные, несвязанные массовые отправки и обход ограничений или проверки. Вы сохраняете права и даёте сопровождающим неисключительное разрешение, необходимое для поддержки, диагностики, сортировки и улучшения. После одобрения может быть создан анонимный публичный Issue без связи с вами или закрытой записью; он может остаться после удаления. Для защиты сервис может ограничивать или отклонять запросы, закрывать спам или отзывать анонимный секрет. Сервис предоставляется как есть и может прерываться, задерживаться, меняться или прекращаться. Не используйте его для экстренных случаев, безопасности людей или оборудования, юридических уведомлений или резервного копирования. Общая связь — через поддержку, безопасность — через SECURITY.md.',
		},
	},
	pl: {
		updated: 'Ostatnia aktualizacja: 20 sierpnia 2026 r.',
		privacy: {
			intro: 'Ta polityka opisuje przetwarzanie danych w funkcjach „Prześlij opinię” i „Moje opinie”. Jest to wysyłka do pomocy uruchamiana przez użytkownika, a nie telemetria ani analiza zachowania. Otwarcie lub edycja formularza niczego nie przesyła; przed wysłaniem widzisz pełną treść i musisz ją wyraźnie potwierdzić.',
			heading: 'Zbieranie, przetwarzanie, przechowywanie, usuwanie i prawa',
			body: 'Wymagane są rodzaj, tytuł i opis; kroki oraz oczekiwany wynik są opcjonalne. Podstawowe dane środowiska są domyślnie włączone, ale można je wyłączyć; obejmują tylko wersje aplikacji i VS Code, rodzinę i główną wersję systemu, architekturę, język, znormalizowane typy hosta i obszaru roboczego, zaufanie, płytkę, język programowania, gotowość narzędzi i stabilne kody błędów. Ostatnie zdarzenia strukturalne są osobną opcją. Kod źródłowy, obszar Blockly, kod wygenerowany, nazwy, ścieżki, identyfikatory urządzeń, porty, Wi-Fi, adresy IP, zmienne środowiska, dane logowania, surowe błędy i dzienniki nie są wysyłane automatycznie. Opcjonalny obraz jest lokalnie kodowany ponownie, pozbawiany metadanych i ograniczony do 1920 pikseli oraz 3 MiB; sprawdź widoczne dane osobowe. Sekret 256-bit pozostaje w VS Code SecretStorage, a serwer zachowuje tylko HMAC. Łącze odzyskiwania używa fragmentu URL; późniejsza sesja HttpOnly, Secure i SameSite trwa najwyżej 24 godziny. Cloudflare może krótko przetwarzać źródłowy IP w celu ochrony, a aplikacja używa tylko wartości HMAC. Tekst trafia do Cloudflare D1, obrazy do prywatnego R2, a kopia robocza do prywatnego GitHub; możliwe jest przetwarzanie transgraniczne. Notatki wewnętrzne są prywatne i widoczne są tylko wyraźnie publiczne odpowiedzi. Zatwierdzony przez właściciela anonimowy publiczny Issue nie jest łączony z prywatnym wpisem. Treść jest przechowywana do usunięcia; idempotencja 7 dni, sesje 24 godziny, a audyt bez treści najwyżej 90 dni. Usunięcie usuwa tekst, wiadomości, obrazy i prywatną treść GitHub, lecz mogą pozostać pusty znacznik, zatwierdzony anonimowy Issue i zaszyfrowane kopie dostawcy. Uczniowie nie powinni wysyłać danych osobowych i w razie potrzeby powinni poprosić dorosłego o pomoc. „Moje opinie” lub łącze umożliwia przeglądanie, uzupełnianie i usuwanie. Bez sekretu nie można potwierdzić własności. Sprawy ogólne kieruj do pomocy, a bezpieczeństwo przez prywatną procedurę SECURITY.md.',
		},
		support: {
			intro: 'Użyj „Prześlij opinię” w edytorze Blockly lub palety poleceń. Konto GitHub nie jest potrzebne.',
			heading: 'Dostęp, usuwanie, bezpieczeństwo i zakres pomocy',
			body: 'Bezpiecznie przechowuj numer i prywatne łącze odzyskiwania; łącze jest poświadczeniem. „Moje opinie” lub łącze pozwala zobaczyć stan i publiczne odpowiedzi, dodać tekst oraz usunąć jedną lub wszystkie opinie. Wyjątki dotyczące kopii dostawcy i zatwierdzonych anonimowych publicznych Issues opisuje polityka prywatności. Nie umieszczaj podatności, ujawnionych sekretów ani błędów kontroli dostępu w zwykłej opinii lub publicznym Issue; użyj GitHub Security Advisory z SECURITY.md. Pomoc jest udzielana w miarę możliwości, bez gwarancji czasu, wdrożenia ani odtworzenia. PlatformIO, GitHub, Cloudflare, VS Code/VSCodium, sprzęt i sieć mogą wpływać na wynik. Zachowaj własną kopię projektu.',
		},
		terms: {
			intro: 'Korzystając z opcjonalnej usługi opinii Singular Blockly, akceptujesz te warunki i politykę prywatności. Produkt pozostaje dostępny bez usługi.',
			heading: 'Cel, obowiązki, prawa i ograniczenia',
			body: 'Usługa służy tylko do problemów z produktem, propozycji funkcji, pytań o użycie i innych opinii; nie obiecuje odpowiedzi, poprawki, wdrożenia, terminu ani wydania. Wysyłaj wyłącznie treści, które możesz udostępnić, i sprawdź tekst oraz obrazy. Zabronione są treści nielegalne, naruszające prawa, nękające, podszywające się lub szkodliwe, spam, automatyczne nadużycia, dane logowania, niepowiązane wysyłki masowe i omijanie limitów lub uwierzytelniania. Zachowujesz prawa i udzielasz opiekunom niewyłącznego pozwolenia potrzebnego do pomocy, diagnostyki, klasyfikacji i ulepszania. Po zatwierdzeniu może powstać anonimowy publiczny Issue bez związku z tobą lub prywatnym wpisem i może pozostać po usunięciu. Dla ochrony usługa może ograniczać lub odrzucać żądania, zamykać spam albo odwołać anonimowe poświadczenie. Jest dostarczana w obecnej postaci i może być przerwana, opóźniona, zmieniona lub zakończona. Nie używaj jej w nagłych przypadkach, dla bezpieczeństwa ludzi lub sprzętu, zawiadomień prawnych ani kopii zapasowych. Kontakt ogólny przez pomoc, bezpieczeństwo przez SECURITY.md.',
		},
	},
	cs: {
		updated: 'Poslední aktualizace: 20. srpna 2026',
		privacy: {
			intro: 'Tyto zásady popisují zpracování dat ve funkcích „Poskytnout zpětnou vazbu“ a „Moje zpětná vazba“. Jde o odeslání podpory zahájené uživatelem, ne o telemetrii ani analýzu chování. Otevření či úprava formuláře nic neodesílá; před odesláním se zobrazí celý obsah a vyžaduje se výslovné potvrzení.',
			heading: 'Shromažďování, zpracování, uchování, odstranění a práva',
			body: 'Povinné jsou typ, název a popis; kroky a očekávaný výsledek jsou volitelné. Základní údaje o prostředí jsou ve výchozím nastavení zapnuté, lze je však vypnout, a zahrnují pouze verze aplikace a VS Code, rodinu a hlavní verzi systému, architekturu, jazyk, normalizované typy hostitele a pracovního prostoru, důvěryhodnost, desku, programovací jazyk, připravenost nástrojů a stabilní kódy chyb. Nedávné strukturované události jsou samostatně volitelné. Zdrojový kód, prostor Blockly, vygenerovaný kód, názvy, cesty, ID zařízení, porty, Wi-Fi, IP adresy, proměnné prostředí, přihlašovací údaje, nezpracované chyby ani protokoly se automaticky neodesílají. Volitelný obrázek se místně překóduje, zbaví metadat a omezí na 1920 pixelů a 3 MiB; zkontrolujte viditelné osobní údaje. Tajemství 256-bit zůstává ve VS Code SecretStorage a server uchovává pouze HMAC. Odkaz pro obnovení používá fragment URL; následná relace HttpOnly, Secure a SameSite trvá nejvýše 24 hodin. Cloudflare může krátce zpracovat zdrojovou IP kvůli ochraně, aplikace používá pouze hodnotu HMAC. Text je v Cloudflare D1, obrázky v soukromém R2 a pracovní kopie v soukromém GitHubu; může dojít k přeshraničnímu zpracování. Interní poznámky jsou soukromé a zobrazí se jen výslovně veřejné odpovědi. Anonymní veřejný Issue schválený vlastníkem není propojen se soukromou položkou. Obsah zůstává do odstranění; idempotence 7 dní, relace 24 hodin a audit bez obsahu nejvýše 90 dní. Odstranění odebere text, zprávy, obrázky a soukromý obsah GitHubu, ale může zůstat prázdná značka, schválený anonymní Issue a šifrované zálohy poskytovatele. Studenti nemají posílat osobní údaje a podle potřeby mají požádat dospělého o pomoc. „Moje zpětná vazba“ nebo odkaz umožňuje čtení, doplnění a odstranění. Bez tajemství nelze prokázat vlastnictví. Obecné dotazy patří podpoře, bezpečnost soukromému postupu v SECURITY.md.',
		},
		support: {
			intro: 'Použijte „Poskytnout zpětnou vazbu“ v editoru Blockly nebo paletu příkazů. Účet GitHub není potřeba.',
			heading: 'Přístup, odstranění, bezpečnost a rozsah podpory',
			body: 'Číslo a soukromý odkaz pro obnovení bezpečně uložte; odkaz je přihlašovací údaj. „Moje zpětná vazba“ nebo odkaz umožňuje zobrazit stav a veřejné odpovědi, přidat text a odstranit jednu či všechny položky. Výjimky pro zálohy poskytovatele a schválené anonymní veřejné Issues popisují zásady ochrany soukromí. Zneužitelné zranitelnosti, uniklá tajemství ani chyby řízení přístupu nepište do běžné zpětné vazby či veřejného Issue; použijte GitHub Security Advisory ze SECURITY.md. Podpora je poskytována podle možností bez záruky času, přijetí nebo reprodukovatelnosti. Výsledek mohou ovlivnit PlatformIO, GitHub, Cloudflare, VS Code/VSCodium, hardware a síť. Uchovávejte vlastní zálohu projektu.',
		},
		terms: {
			intro: 'Použitím volitelné služby zpětné vazby Singular Blockly přijímáte tyto podmínky a zásady ochrany soukromí. Produkt lze používat i bez služby.',
			heading: 'Účel, odpovědnost, práva a omezení',
			body: 'Služba je určena jen pro problémy produktu, návrhy funkcí, dotazy k použití a další zpětnou vazbu; neslibuje odpověď, opravu, přijetí, termín ani vydání. Odesílejte jen obsah, který smíte sdílet, a předem zkontrolujte text a obrázky. Zakázán je nezákonný, porušující, obtěžující, vydávající se za jiného nebo škodlivý obsah, spam, automatizované zneužití, přihlašovací údaje, nesouvisející hromadný obsah a obcházení limitů či ověření. Práva si ponecháváte a správcům udělujete nevýhradní oprávnění nutné k podpoře, diagnostice, třídění a zlepšování. Po schválení může vzniknout anonymní veřejný Issue bez vazby na vás či soukromou položku a může zůstat po odstranění. Kvůli ochraně může služba omezit či odmítnout požadavky, zavřít spam nebo zrušit anonymní údaj. Je poskytována tak, jak je, a může být přerušena, zpožděna, změněna či ukončena. Nepoužívejte ji pro nouzové situace, bezpečnost lidí či zařízení, právní oznámení ani zálohy. Obecný kontakt přes podporu, bezpečnost přes SECURITY.md.',
		},
	},
	hu: {
		updated: 'Utolsó frissítés: 2026. augusztus 20.',
		privacy: {
			intro: 'Ez a szabályzat ismerteti az adatkezelést a „Visszajelzés küldése” és a „Saját visszajelzések” funkcióban. Ez a felhasználó által indított támogatási küldés, nem telemetria vagy viselkedéselemzés. Az űrlap megnyitása vagy szerkesztése nem küld adatot; küldés előtt a teljes tartalom látható és kifejezett megerősítés szükséges.',
			heading: 'Gyűjtés, kezelés, megőrzés, törlés és jogok',
			body: 'A típus, cím és leírás kötelező; a lépések és a várt eredmény választható. Az alap környezeti adatok alapból be vannak kapcsolva, de kikapcsolhatók, és csak az alkalmazás és a VS Code verzióját, az operációs rendszer családját és főverzióját, az architektúrát, nyelvet, a normalizált gazda- és munkaterülettípust, a megbízhatóságot, a panelt, a programozási nyelvet, az eszközök készültségét és stabil hibakódokat tartalmazzák. A legutóbbi strukturált események külön választhatók. Forráskód, Blockly-munkaterület, generált kód, nevek, útvonalak, eszközazonosítók, portok, Wi-Fi, IP-címek, környezeti változók, hitelesítő adatok, nyers hibák és naplók nem kerülnek automatikusan elküldésre. Az opcionális kép helyben újrakódolódik, metaadatai törlődnek, és 1920 képpontra, illetve 3 MiB-ra korlátozott; ellenőrizze a látható személyes adatokat. A 256-bit titok a VS Code SecretStorage-ban marad, a szerver csak HMAC-ot tárol. A helyreállítási hivatkozás URL-töredéket használ; az ezt követő HttpOnly, Secure és SameSite munkamenet legfeljebb 24 órás. A Cloudflare védelem céljából röviden kezelheti a forrás IP-t, az alkalmazás csak HMAC-értéket használ. A szöveg Cloudflare D1-ben, a kép privát R2-ben, a karbantartási másolat privát GitHubon van; határokon átnyúló kezelés lehetséges. A belső jegyzetek privátak, csak a kifejezetten nyilvános válaszok látszanak. A tulajdonos által jóváhagyott névtelen nyilvános Issue nincs a privát elemhez kötve. A tartalom törlésig marad; az idempotencia 7 napig, a munkamenet 24 óráig, a tartalommentes napló legfeljebb 90 napig. A törlés eltávolítja a szöveget, üzeneteket, képet és a privát GitHub-tartalmat, de tartalommentes jelző, jóváhagyott névtelen Issue és titkosított szolgáltatói mentés maradhat. A tanulók ne küldjenek személyes adatot, és szükség esetén kérjenek felnőtt segítséget. A „Saját visszajelzések” vagy a hivatkozás lehetővé teszi a megtekintést, bővítést és törlést. A titok nélkül a tulajdon nem igazolható. Általános ügyekben a támogatást, biztonsági ügyben a SECURITY.md privát eljárását használja.',
		},
		support: {
			intro: 'Használja a Blockly-szerkesztő „Visszajelzés küldése” gombját vagy a parancspalettát. GitHub-fiók nem szükséges.',
			heading: 'Hozzáférés, törlés, biztonság és a támogatás köre',
			body: 'Őrizze biztonságosan a számot és a privát helyreállítási hivatkozást; a hivatkozás hitelesítő adat. A „Saját visszajelzések” vagy a hivatkozás segítségével megtekintheti az állapotot és a nyilvános válaszokat, szöveget adhat hozzá, valamint egy vagy minden elemet törölhet. A szolgáltatói mentések és a jóváhagyott névtelen nyilvános Issues kivételeit az adatvédelmi szabályzat ismerteti. Kihasználható sebezhetőséget, kiszivárgott titkot vagy hozzáférés-vezérlési hibát ne írjon általános visszajelzésbe vagy nyilvános Issue-ba; használja a SECURITY.md GitHub Security Advisory eljárását. A támogatás lehetőség szerint működik, válaszidőre, elfogadásra vagy reprodukálhatóságra nincs garancia. A PlatformIO, GitHub, Cloudflare, VS Code/VSCodium, hardver és hálózat befolyásolhatja az eredményt. Tartsa meg saját projektmentését.',
		},
		terms: {
			intro: 'A választható Singular Blockly visszajelzési szolgáltatás használatával elfogadja ezeket a feltételeket és az adatvédelmi szabályzatot. A termék a szolgáltatás nélkül is használható.',
			heading: 'Cél, felelősség, jogok és korlátozások',
			body: 'A szolgáltatás csak termékhibákra, funkciójavaslatokra, használati kérdésekre és egyéb visszajelzésre szolgál; nem ígér választ, javítást, elfogadást, ütemezést vagy kiadást. Csak megosztható tartalmat küldjön, és ellenőrizze a szöveget és képet. Tilos a jogellenes, jogsértő, zaklató, megszemélyesítő vagy káros tartalom, spam, automatizált visszaélés, hitelesítő adat, nem kapcsolódó tömeges tartalom és a korlátok vagy hitelesítés megkerülése. Jogait megtartja, a karbantartóknak pedig a támogatáshoz, diagnózishoz, osztályozáshoz és fejlesztéshez szükséges nem kizárólagos engedélyt ad. Jóváhagyás után létrejöhet önhöz vagy a privát elemhez nem kötött névtelen nyilvános Issue, amely a törlés után is megmaradhat. Védelem céljából a szolgáltatás korlátozhat, elutasíthat, spamet zárhat vagy anonim hitelesítőt vonhat vissza. A szolgáltatás jelen állapotban érhető el, megszakadhat, késhet, változhat vagy megszűnhet. Ne használja vészhelyzethez, személy- vagy eszközbiztonsághoz, jogi értesítéshez vagy mentéshez. Általános kapcsolat a támogatáson, biztonsági kapcsolat a SECURITY.md-n keresztül.',
		},
	},
	bg: {
		updated: 'Последна актуализация: 20 август 2026 г.',
		privacy: {
			intro: 'Тази политика описва обработването на данни във „Връзка с нас“ и „Моята обратна връзка“. Това е изпращане към поддръжката, започнато от потребителя, а не телеметрия или анализ на поведението. Отварянето или редактирането на формуляра не изпраща данни; преди изпращане се показва цялото съдържание и се изисква изрично потвърждение.',
			heading: 'Събиране, обработване, съхранение, изтриване и права',
			body: 'Задължителни са видът, заглавието и описанието; стъпките и очакваният резултат са по избор. Основните данни за средата са включени по подразбиране, но могат да се изключат, и съдържат само версии на приложението и VS Code, семейство и основна версия на системата, архитектура, език, нормализирани типове хост и работно пространство, доверие, платка, програмен език, готовност на инструментите и стабилни кодове за грешки. Последните структурирани събития са отделна опция. Изходен код, Blockly пространство, генериран код, имена, пътища, идентификатори на устройства, портове, Wi-Fi, IP адреси, променливи на средата, идентификационни данни, необработени грешки и журнали не се изпращат автоматично. Изображението по избор се прекодира локално, метаданните се премахват и се ограничава до 1920 пиксела и 3 MiB; проверете видимите лични данни. Тайната 256-bit остава във VS Code SecretStorage, а сървърът пази само HMAC. Връзката за възстановяване използва URL фрагмент; следващата сесия HttpOnly, Secure и SameSite е най-много 24 часа. Cloudflare може за кратко да обработи изходния IP за защита, а приложението използва само HMAC стойност. Текстът е в Cloudflare D1, изображенията в частен R2, а работното копие в частен GitHub; възможно е трансгранично обработване. Вътрешните бележки са частни и се виждат само изрично публични отговори. Одобрен от собственика анонимен публичен Issue не се свързва с частния запис. Съдържанието се пази до изтриване; идемпотентност 7 дни, сесии 24 часа и одит без съдържание до 90 дни. Изтриването премахва текст, съобщения, изображения и частното съдържание в GitHub, но може да останат празен маркер, одобрен анонимен Issue и криптирани резервни копия на доставчика. Учениците не трябва да изпращат лични данни и при нужда трябва да потърсят възрастен. „Моята обратна връзка“ или връзката позволява преглед, допълване и изтриване. Без тайната собствеността не може да се докаже. Общи въпроси се подават към поддръжката, а сигурността чрез частната процедура в SECURITY.md.',
		},
		support: {
			intro: 'Използвайте „Връзка с нас“ в редактора Blockly или палитрата с команди. Не е необходим акаунт в GitHub.',
			heading: 'Достъп, изтриване, сигурност и обхват на поддръжката',
			body: 'Пазете номера и частната връзка за възстановяване; връзката е идентификационен секрет. Чрез „Моята обратна връзка“ или връзката можете да видите състоянието и публичните отговори, да добавите текст и да изтриете една или всички записи. Изключенията за резервни копия и одобрени анонимни публични Issues са описани в политиката за поверителност. Не пишете използваеми уязвимости, изтекли тайни или проблеми с контрола на достъпа в обща обратна връзка или публичен Issue; използвайте GitHub Security Advisory от SECURITY.md. Поддръжката е според възможностите, без гаранция за срок, приемане или възпроизводимост. PlatformIO, GitHub, Cloudflare, VS Code/VSCodium, хардуерът и мрежата могат да влияят. Пазете собствено резервно копие на проекта.',
		},
		terms: {
			intro: 'С използването на незадължителната услуга за обратна връзка на Singular Blockly приемате тези условия и политиката за поверителност. Продуктът може да се използва и без услугата.',
			heading: 'Цел, отговорности, права и ограничения',
			body: 'Услугата е само за проблеми с продукта, предложения за функции, въпроси за употреба и друга обратна връзка; тя не обещава отговор, поправка, приемане, график или издание. Изпращайте само съдържание, което имате право да споделяте, и проверявайте текста и изображенията. Забранени са незаконно, нарушаващо права, тормозещо, представящо се за друг или вредно съдържание, спам, автоматизирана злоупотреба, идентификационни данни, несвързано масово съдържание и заобикаляне на ограничения или удостоверяване. Запазвате правата си и давате на поддържащите неизключително разрешение, необходимо за поддръжка, диагностика, класиране и подобряване. След одобрение може да се създаде анонимен публичен Issue без връзка с вас или частния запис и той може да остане след изтриване. За защита услугата може да ограничава, отхвърля, затваря спам или отнема анонимен секрет. Предоставя се във вида, в който е, и може да бъде прекъсната, забавена, променена или спряна. Не я използвайте за спешни случаи, безопасност на хора или техника, правни уведомления или резервни копия. Общ контакт чрез поддръжката, сигурност чрез SECURITY.md.',
		},
	},
	tr: {
		updated: 'Son güncelleme: 20 Ağustos 2026',
		privacy: {
			intro: 'Bu politika, “Geri bildirim gönder” ve “Geri bildirimlerim” özelliklerindeki veri işlemeyi açıklar. Bu, kullanıcı tarafından başlatılan bir destek gönderimidir; telemetri veya davranış analizi değildir. Formu açmak ya da düzenlemek veri göndermez; gönderimden önce tüm içerik gösterilir ve açık onay gerekir.',
			heading: 'Toplama, işleme, saklama, silme ve haklar',
			body: 'Tür, başlık ve açıklama zorunludur; adımlar ve beklenen sonuç isteğe bağlıdır. Temel ortam bilgileri varsayılan olarak açıktır ancak kapatılabilir ve yalnızca uygulama ile VS Code sürümleri, işletim sistemi ailesi ve ana sürümü, mimari, dil, normalleştirilmiş ana bilgisayar ve çalışma alanı türleri, güven durumu, kart, programlama dili, araç hazırlığı ve kararlı hata kodlarıyla sınırlıdır. Son yapılandırılmış olaylar ayrıca isteğe bağlıdır. Kaynak kodu, Blockly çalışma alanı, üretilmiş kod, adlar, yollar, cihaz kimlikleri, bağlantı noktaları, Wi-Fi, IP adresleri, ortam değişkenleri, kimlik bilgileri, ham hatalar ve günlükler otomatik gönderilmez. İsteğe bağlı görüntü yerel olarak yeniden kodlanır, meta verileri kaldırılır ve 1920 piksel ile 3 MiB sınırına alınır; görünen kişisel verileri kontrol edin. 256-bit sır VS Code SecretStorage’da kalır, sunucu yalnızca HMAC saklar. Kurtarma bağlantısı URL parçasını kullanır; sonraki HttpOnly, Secure ve SameSite oturumu en fazla 24 saat sürer. Cloudflare koruma için kaynak IP’yi kısa süre işleyebilir, uygulama yalnızca HMAC değeri kullanır. Metin Cloudflare D1’de, görüntüler özel R2’de, bakım kopyası özel GitHub’da saklanır; sınır ötesi işleme olabilir. İç notlar özeldir ve yalnızca açıkça herkese açık yanıtlar görünür. Sorumlu tarafından onaylanan anonim herkese açık Issue, özel kayıtla ilişkilendirilmez. İçerik silinene kadar tutulur; eşgüçlülük kayıtları 7 gün, oturumlar 24 saat, içeriksiz denetim kayıtları en fazla 90 gün saklanır. Silme; metni, iletileri, görüntüleri ve özel GitHub içeriğini kaldırır ancak içeriksiz işaret, onaylı anonim Issue ve sağlayıcının şifreli yedekleri kalabilir. Öğrenciler kişisel veri göndermemeli ve gerektiğinde bir yetişkinden yardım istemelidir. “Geri bildirimlerim” veya bağlantı görüntüleme, ekleme ve silme sağlar. Sır olmadan sahiplik kanıtlanamaz. Genel konular için desteği, güvenlik için SECURITY.md’deki özel süreci kullanın.',
		},
		support: {
			intro: 'Blockly düzenleyicisindeki “Geri bildirim gönder” düğmesini veya komut paletini kullanın. GitHub hesabı gerekmez.',
			heading: 'Erişim, silme, güvenlik ve destek kapsamı',
			body: 'Numarayı ve özel kurtarma bağlantısını güvenle saklayın; bağlantı bir kimlik bilgisidir. “Geri bildirimlerim” veya bağlantı ile durumu ve herkese açık yanıtları görebilir, metin ekleyebilir ve bir ya da tüm kayıtları silebilirsiniz. Sağlayıcı yedekleri ve onaylanmış anonim herkese açık Issues istisnaları gizlilik politikasında açıklanır. Kullanılabilir güvenlik açıklarını, sızmış sırları veya erişim denetimi hatalarını genel geri bildirime ya da herkese açık Issue’ya yazmayın; SECURITY.md’de belirtilen GitHub Security Advisory yolunu kullanın. Destek en iyi çaba ile sunulur; yanıt süresi, kabul veya yeniden üretilebilirlik garantisi yoktur. PlatformIO, GitHub, Cloudflare, VS Code/VSCodium, donanım ve ağ sonucu etkileyebilir. Kendi proje yedeğinizi saklayın.',
		},
		terms: {
			intro: 'İsteğe bağlı Singular Blockly geri bildirim hizmetini kullanarak bu koşulları ve gizlilik politikasını kabul edersiniz. Ürün, hizmet olmadan da kullanılabilir.',
			heading: 'Amaç, sorumluluklar, haklar ve sınırlamalar',
			body: 'Hizmet yalnızca ürün sorunları, özellik önerileri, kullanım soruları ve diğer geri bildirimler içindir; yanıt, düzeltme, kabul, takvim veya sürüm sözü vermez. Yalnızca paylaşma hakkınız olan içeriği gönderin ve metinle görüntüleri inceleyin. Yasa dışı, hak ihlal eden, taciz edici, başkasını taklit eden veya zararlı içerik, spam, otomatik kötüye kullanım, kimlik bilgileri, ilgisiz toplu içerik ve sınırları ya da kimlik doğrulamayı aşmak yasaktır. Haklarınızı korur ve bakımcılara destek, tanılama, sınıflandırma ve iyileştirme için gereken münhasır olmayan izni verirsiniz. Onaydan sonra sizinle veya özel kayıtla bağlantısı olmayan anonim herkese açık Issue oluşturulabilir ve silme sonrasında kalabilir. Koruma için hizmet sınırlayabilir, reddedebilir, spam’i kapatabilir veya anonim kimliği iptal edebilir. Hizmet olduğu gibi sunulur ve kesilebilir, gecikebilir, değişebilir veya sona erebilir. Acil durum, insan ya da donanım güvenliği, yasal bildirim veya yedekleme için kullanmayın. Genel iletişim destek üzerinden, güvenlik iletişimi SECURITY.md üzerinden yapılır.',
		},
	},
} as const satisfies Record<CompactPolicyLocale, CompactPolicyCopy>;
