/**
 * @license
 * Copyright 2025 Singular Blockly Contributors
 * SPDX-License-Identifier: Apache-2.0
 */

import { CYBERBRICK_OTA_PROTOCOL_VERSION, CYBERBRICK_OTA_REMOTE_PATH } from '../types/cyberbrickUpload';

export const CYBERBRICK_OTA_AGENT_VERSION = '1.3.0';
export const CYBERBRICK_OTA_RC_MAIN_BOOTSTRAP_START = '# Singular Blockly CyberBrick OTA bootstrap START';
export const CYBERBRICK_OTA_RC_MAIN_BOOTSTRAP_END = '# Singular Blockly CyberBrick OTA bootstrap END';

export interface CyberBrickOtaAgentConfig {
	deviceId: string;
	otaToken: string;
	otaPort: number;
}

function escapeRegExp(value: string): string {
	return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

export function buildCyberBrickRcMainOtaBootstrap(): string {
	return [
		CYBERBRICK_OTA_RC_MAIN_BOOTSTRAP_START,
		'try:',
		'    import cyberbrick_ota_agent as _singular_blockly_ota_agent',
		'    _singular_blockly_ota_agent.start_background(False)',
		'except Exception:',
		'    pass',
		CYBERBRICK_OTA_RC_MAIN_BOOTSTRAP_END,
	].join('\n');
}

export function stripCyberBrickRcMainOtaBootstrap(code: string): string {
	const pattern = new RegExp(
		`\\n?${escapeRegExp(CYBERBRICK_OTA_RC_MAIN_BOOTSTRAP_START)}[\\s\\S]*?${escapeRegExp(CYBERBRICK_OTA_RC_MAIN_BOOTSTRAP_END)}\\n?`,
		'g'
	);
	return code.replace(pattern, '\n').replace(/^\n+/, '');
}

export function withCyberBrickRcMainOtaBootstrap(code: string): string {
	const cleanedCode = stripCyberBrickRcMainOtaBootstrap(code).replace(/^\n+/, '');
	return `${buildCyberBrickRcMainOtaBootstrap()}\n\n${cleanedCode}`;
}

/**
 * Builds the device-side MicroPython OTA agent source.
 * The returned string intentionally contains device-side credentials so callers must never log it.
 */
export function buildCyberBrickOtaAgentSource(config: CyberBrickOtaAgentConfig): string {
	return `# CyberBrick OTA agent v${CYBERBRICK_OTA_AGENT_VERSION}
# Generated by Singular Blockly. Do not print secrets from this file.
import ubinascii
import uhashlib
import ujson
try:
	import usocket as socket
except ImportError:
	import socket
try:
	import cyberbrick_ota_config as cfg
except Exception:
	cfg = None


def _cfg(name, default):
	try:
		return getattr(cfg, name, default) if cfg else default
	except Exception:
		return default


DEVICE_ID = _cfg('DEVICE_ID', ${JSON.stringify(config.deviceId)})
OTA_TOKEN = _cfg('OTA_TOKEN', ${JSON.stringify(config.otaToken)})
OTA_PORT = _cfg('OTA_PORT', ${JSON.stringify(config.otaPort)})
SSID = _cfg('SSID', '')
WIFI_PASSWORD = _cfg('WIFI_PASSWORD', '')
AGENT_VERSION = ${JSON.stringify(CYBERBRICK_OTA_AGENT_VERSION)}
PROTOCOL_VERSION = ${JSON.stringify(CYBERBRICK_OTA_PROTOCOL_VERSION)}
REMOTE_PATH = ${JSON.stringify(CYBERBRICK_OTA_REMOTE_PATH)}
_SERVER_STARTED = False
_reset_pending = [False]


def _sha256(data):
	digest = uhashlib.sha256(data).digest()
	return ubinascii.hexlify(digest).decode()


def _json_response(status, payload):
	body = ujson.dumps(payload)
	return 'HTTP/1.1 %s OK\\r\\nContent-Type: application/json\\r\\nContent-Length: %d\\r\\nConnection: close\\r\\n\\r\\n%s' % (status, len(body), body)


def _unauthorized():
	return _json_response(401, {'error': 'token-rejected', 'deviceId': DEVICE_ID})


def _headers_ok(headers):
	auth = headers.get('authorization', '')
	device_id = headers.get('x-cyberbrick-device-id', '')
	protocol = headers.get('x-cyberbrick-protocol-version', '')
	return auth == ('Bearer ' + OTA_TOKEN) and device_id == DEVICE_ID and protocol == str(PROTOCOL_VERSION)


def _current_ip():
	try:
		import network
		wlan = network.WLAN(network.STA_IF)
		return wlan.ifconfig()[0] if wlan.isconnected() else ''
	except Exception:
		return ''


def _connect_wifi(timeout_quarters=80):
	try:
		import network
		import time
		wlan = network.WLAN(network.STA_IF)
		wlan.active(True)
		if wlan.isconnected():
			return wlan.ifconfig()[0]
		if SSID:
			wlan.connect(SSID, WIFI_PASSWORD)
			for _ in range(timeout_quarters):
				if wlan.isconnected():
					return wlan.ifconfig()[0]
				time.sleep(0.25)
	except Exception:
		return ''
	return ''


def _health():
	return _json_response(200, {
		'deviceId': DEVICE_ID,
		'agentVersion': AGENT_VERSION,
		'protocolVersion': PROTOCOL_VERSION,
		'supportedProtocolVersions': [PROTOCOL_VERSION],
		'appPath': REMOTE_PATH,
		'ipAddress': _current_ip(),
		'status': 'ready',
	})


def _upload_raw(client, headers, leftover):
	device_id = headers.get('x-cyberbrick-device-id', '')
	expected_sha = headers.get('x-singular-content-sha256', '')
	operation_id = headers.get('x-singular-operation-id', '')
	content_length = 0
	try:
		content_length = int(headers.get('content-length', 0))
	except Exception:
		pass
	if device_id != DEVICE_ID:
		return _json_response(403, {'error': 'identity-mismatch', 'deviceId': DEVICE_ID})
	sha = uhashlib.sha256()
	received = 0
	with open(REMOTE_PATH, 'wb') as f:
		if leftover:
			f.write(leftover)
			sha.update(leftover)
			received += len(leftover)
		while received < content_length:
			chunk = client.recv(min(1024, content_length - received))
			if not chunk:
				break
			f.write(chunk)
			sha.update(chunk)
			received += len(chunk)
	content_sha = ubinascii.hexlify(sha.digest()).decode()
	if content_sha != expected_sha:
		return _json_response(400, {'error': 'write-failed', 'contentSha256': content_sha})
	_reset_pending[0] = True
	return _json_response(200, {
		'operationId': operation_id,
		'deviceId': DEVICE_ID,
		'remotePath': REMOTE_PATH,
		'bytesWritten': received,
		'contentSha256': content_sha,
		'restarted': True,
		'status': 'written',
	})


def _parse_headers(raw):
	header_text, _, body = raw.partition('\\r\\n\\r\\n')
	lines = header_text.split('\\r\\n')
	request = lines[0] if lines else ''
	headers = {}
	for line in lines[1:]:
		if ':' in line:
			k, v = line.split(':', 1)
			headers[k.lower()] = v.strip()
	return request, headers, body


def _recv_headers(client):
	raw = b''
	while b'\\r\\n\\r\\n' not in raw:
		chunk = client.recv(256)
		if not chunk:
			break
		raw += chunk
	header_bytes, _, leftover = raw.partition(b'\\r\\n\\r\\n')
	return header_bytes.decode(), leftover


def _create_server_socket():
	s = socket.socket()
	s.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
	s.bind(('0.0.0.0', OTA_PORT))
	s.listen(1)
	return s


def serve_forever(sock=None):
	_connect_wifi()
	s = sock or _create_server_socket()
	while True:
		client, _addr = s.accept()
		try:
			header_text, leftover = _recv_headers(client)
			request, headers, _ = _parse_headers(header_text + '\\r\\n\\r\\n')
			if not _headers_ok(headers):
				client.send(_unauthorized())
			elif request.startswith('GET /api/v1/health'):
				client.send(_health())
			elif request.startswith('POST /api/v1/upload'):
				client.send(_upload_raw(client, headers, leftover))
			else:
				client.send(_json_response(404, {'error': 'not-found'}))
		except Exception as exc:
			try:
				client.send(_json_response(500, {'error': 'agent-error', 'message': str(exc)}))
			except Exception:
				pass
		client.close()
		if _reset_pending[0]:
			try:
				import time
				time.sleep_ms(300)
			except Exception:
				pass
			import machine
			machine.reset()


def start_background(wait_for_wifi=True):
	global _SERVER_STARTED
	ip = _connect_wifi() if wait_for_wifi else _current_ip()
	if _SERVER_STARTED:
		return {'started': True, 'ipAddress': ip or _current_ip(), 'mode': 'already-running'}
	server_socket = None
	try:
		server_socket = _create_server_socket()
		import _thread
		_thread.start_new_thread(serve_forever, (server_socket,))
		_SERVER_STARTED = True
		return {'started': True, 'ipAddress': ip or _current_ip(), 'mode': 'thread'}
	except Exception as exc:
		try:
			if server_socket:
				server_socket.close()
		except Exception:
			pass
		return {'started': False, 'ipAddress': ip or _current_ip(), 'error': str(exc)}


if __name__ == '__main__':
	serve_forever()
`;
}
